/**
 * Spec 054 — single typed product-surface registry.
 * Sidebar, bootstrap prediction, module tabs and route presentation share these rows.
 */

import type { ProductSurfaceDefinition } from './product-surface.models';
import { CRM_PLATFORM_ROLES, STAFF_CAPABILITY } from './product-surface.models';

const personalMain: ProductSurfaceDefinition[] = [
  {
    id: 'personal.discover',
    labelKey: 'nav.home',
    iconId: 'home',
    path: '/discover',
    spaces: ['personal'],
    sectionId: 'space-main',
    sectionTitleKey: 'spaces.nav.group.main',
    order: 10,
    exact: true,
  },
  {
    id: 'personal.search',
    labelKey: 'nav.search',
    iconId: 'search',
    path: '/search',
    spaces: ['personal'],
    sectionId: 'space-main',
    sectionTitleKey: 'spaces.nav.group.main',
    order: 20,
    exact: true,
  },
];

const personalLibrary: ProductSurfaceDefinition[] = [
  {
    id: 'personal.tracks',
    labelKey: 'nav.tracks',
    iconId: 'catalog',
    path: '/tracks',
    spaces: ['personal'],
    sectionId: 'space-library',
    sectionTitleKey: 'spaces.nav.group.library',
    order: 30,
    exact: true,
  },
  {
    id: 'personal.playlists',
    labelKey: 'nav.playlists',
    iconId: 'playlists',
    path: '/playlists',
    spaces: ['personal'],
    sectionId: 'space-library',
    sectionTitleKey: 'spaces.nav.group.library',
    order: 40,
    exact: false,
  },
  {
    id: 'personal.liked',
    labelKey: 'nav.liked',
    iconId: 'liked',
    path: '/liked',
    spaces: ['personal'],
    sectionId: 'space-library',
    sectionTitleKey: 'spaces.nav.group.library',
    order: 50,
    exact: true,
  },
  {
    id: 'personal.history',
    labelKey: 'nav.history',
    iconId: 'activity',
    path: '/history',
    spaces: ['personal'],
    sectionId: 'space-library',
    sectionTitleKey: 'spaces.nav.group.library',
    order: 60,
    exact: true,
  },
  {
    id: 'personal.activity',
    labelKey: 'nav.activity',
    iconId: 'activity',
    path: '/activity',
    spaces: ['personal'],
    sectionId: 'space-library',
    sectionTitleKey: 'spaces.nav.group.library',
    order: 70,
    exact: true,
  },
];

const personalAccount = (spaces: ProductSurfaceDefinition['spaces'], includeSettings: boolean): ProductSurfaceDefinition[] => {
  const items: ProductSurfaceDefinition[] = [
    {
      id: 'account.plans',
      labelKey: 'nav.personal.plans',
      iconId: 'plans',
      path: '/account/plans',
      spaces,
      sectionId: 'space-account',
      sectionTitleKey: 'spaces.nav.group.account',
      order: 200,
      exact: true,
    },
    {
      id: 'account.subscription',
      labelKey: 'nav.personal.subscription',
      iconId: 'account',
      path: '/account/subscription',
      spaces,
      sectionId: 'space-account',
      sectionTitleKey: 'spaces.nav.group.account',
      order: 210,
      exact: true,
    },
    {
      id: 'account.household',
      labelKey: 'nav.personal.household',
      iconId: 'team',
      path: '/account/household',
      spaces,
      sectionId: 'space-account',
      sectionTitleKey: 'spaces.nav.group.account',
      order: 220,
      exact: true,
    },
    {
      id: 'account.billing',
      labelKey: 'nav.personal.billing',
      iconId: 'billing',
      path: '/account/billing',
      spaces,
      sectionId: 'space-account',
      sectionTitleKey: 'spaces.nav.group.account',
      order: 230,
      exact: true,
    },
  ];
  if (includeSettings) {
    items.push({
      id: 'account.settings',
      labelKey: 'nav.settings',
      iconId: 'settings',
      path: '/settings',
      spaces,
      sectionId: 'space-account',
      sectionTitleKey: 'spaces.nav.group.account',
      order: 240,
      exact: true,
    });
  }
  return items;
};

const personalEntry: ProductSurfaceDefinition[] = [
  {
    id: 'entry.artist_claim',
    labelKey: 'firstAccess.artist',
    iconId: 'artist',
    path: '/artist-space/claim',
    spaces: ['personal'],
    sectionId: 'space-entry',
    sectionTitleKey: 'firstAccess.group',
    order: 300,
    exact: true,
  },
  {
    id: 'entry.organization_new',
    labelKey: 'firstAccess.organization',
    iconId: 'organization',
    path: '/organizations/new',
    spaces: ['personal'],
    sectionId: 'space-entry',
    sectionTitleKey: 'firstAccess.group',
    order: 310,
    exact: true,
  },
];

const orgMain: ProductSurfaceDefinition[] = [
  {
    id: 'org.workpanel',
    labelKey: 'nav.workpanel',
    iconId: 'workpanel',
    path: '/workpanel',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-org-main',
    sectionTitleKey: 'spaces.nav.group.main',
    order: 10,
    exact: true,
  },
  {
    id: 'org.catalog',
    labelKey: 'nav.catalogHub',
    iconId: 'catalog',
    path: '/catalog',
    spaces: ['organization'],
    organizationTier: 'operational',
    capabilitiesAny: ['artist.view', 'publishing.view', 'rights.view'],
    sectionId: 'space-org-main',
    sectionTitleKey: 'spaces.nav.group.main',
    order: 20,
    exact: true,
    contextGroup: 'catalog',
    tabLabel: 'Resumen',
  },
  {
    id: 'org.hub',
    labelKey: 'spaces.nav.org.summary',
    iconId: 'organization',
    path: '/organizations/:id',
    spaces: ['organization'],
    organizationTier: 'onboarding',
    capability: 'organization.view',
    sectionId: 'space-org-main',
    sectionTitleKey: 'spaces.nav.group.main',
    order: 30,
    exact: true,
    contextGroup: 'organization',
    tabLabel: 'Resumen',
  },
  {
    id: 'org.reports',
    labelKey: 'spaces.nav.reports',
    iconId: 'reports',
    path: '/reports',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'report.view',
    sectionId: 'space-org-main',
    sectionTitleKey: 'spaces.nav.group.main',
    order: 40,
    exact: true,
    contextGroup: 'reports',
  },
];

const orgPlanBilling: ProductSurfaceDefinition[] = [
  {
    id: 'org.subscriptions.plans',
    labelKey: 'nav.subscriptions.plans',
    iconId: 'plans',
    path: '/subscriptions/plans',
    spaces: ['organization'],
    organizationTier: 'onboarding',
    capability: 'subscription.view',
    sectionId: 'space-org-plan',
    sectionTitleKey: 'spaces.nav.org.planBilling',
    order: 50,
  },
  {
    id: 'org.subscriptions.overview',
    labelKey: 'nav.subscriptions.overview',
    iconId: 'account',
    path: '/subscriptions/overview',
    spaces: ['organization'],
    organizationTier: 'onboarding',
    capability: 'subscription.view',
    sectionId: 'space-org-plan',
    sectionTitleKey: 'spaces.nav.org.planBilling',
    order: 60,
    contextGroup: 'organization',
    tabLabel: 'Plan y facturación',
    matchPrefixes: ['/subscriptions', '/billing'],
  },
  {
    id: 'org.billing.invoices',
    labelKey: 'nav.billing.invoices',
    iconId: 'billing',
    path: '/billing/invoices',
    spaces: ['organization'],
    organizationTier: 'recovery',
    capability: 'invoice.view',
    sectionId: 'space-org-plan',
    sectionTitleKey: 'spaces.nav.org.planBilling',
    order: 70,
  },
  {
    id: 'org.billing.profile',
    labelKey: 'nav.billing.profile',
    iconId: 'settings',
    path: '/billing/profile',
    spaces: ['organization'],
    organizationTier: 'recovery',
    capability: 'billing.view',
    sectionId: 'space-org-plan',
    sectionTitleKey: 'spaces.nav.org.planBilling',
    order: 80,
  },
];

/** Staff / CRM-role commercial surfaces — hub in sidebar; children as module tabs. */
const orgCrm: ProductSurfaceDefinition[] = [
  {
    id: 'org.crm.dashboard',
    labelKey: 'nav.crm.dashboard',
    iconId: 'team',
    path: '/crm/dashboard',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    platformRolesAny: CRM_PLATFORM_ROLES,
    sectionId: 'space-org-crm',
    sectionTitleKey: 'nav.section.crm',
    order: 90,
    contextGroup: 'crm',
    tabLabel: 'Resumen',
    exact: true,
    matchPrefixes: ['/crm/dashboard'],
  },
  {
    id: 'org.crm.prospects',
    labelKey: 'nav.crm.prospects',
    iconId: 'artist',
    path: '/crm/prospects',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    platformRolesAny: CRM_PLATFORM_ROLES,
    sectionId: 'space-crm-tabs',
    sectionTitleKey: 'nav.section.crm',
    order: 100,
    contextGroup: 'crm',
    tabLabel: 'Prospectos',
    matchPrefixes: ['/crm/prospects'],
  },
  {
    id: 'org.crm.contacts',
    labelKey: 'nav.crm.contacts',
    iconId: 'team',
    path: '/crm/contacts',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    platformRolesAny: CRM_PLATFORM_ROLES,
    sectionId: 'space-crm-tabs',
    sectionTitleKey: 'nav.section.crm',
    order: 105,
    contextGroup: 'crm',
    tabLabel: 'Contactos',
    matchPrefixes: ['/crm/contacts'],
  },
  {
    id: 'org.crm.opportunities',
    labelKey: 'nav.crm.opportunities',
    iconId: 'strategic',
    path: '/crm/opportunities',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    platformRolesAny: CRM_PLATFORM_ROLES,
    sectionId: 'space-crm-tabs',
    sectionTitleKey: 'nav.section.crm',
    order: 110,
    contextGroup: 'crm',
    tabLabel: 'Oportunidades',
    matchPrefixes: ['/crm/opportunities'],
  },
  {
    id: 'org.crm.approvals',
    labelKey: 'nav.crm.approvals',
    iconId: 'contracts',
    path: '/crm/approvals',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    platformRolesAny: CRM_PLATFORM_ROLES,
    sectionId: 'space-crm-tabs',
    sectionTitleKey: 'nav.section.crm',
    order: 115,
    contextGroup: 'crm',
    tabLabel: 'Aprobaciones',
    matchPrefixes: ['/crm/approvals'],
  },
  {
    id: 'org.crm.audit',
    labelKey: 'nav.crm.audit',
    iconId: 'activity',
    path: '/crm/audit',
    spaces: ['organization'],
    staffCapability: STAFF_CAPABILITY.shell,
    platformRolesAny: CRM_PLATFORM_ROLES,
    sectionId: 'space-crm-tabs',
    sectionTitleKey: 'nav.section.crm',
    order: 118,
    contextGroup: 'crm',
    tabLabel: 'Auditoría',
    matchPrefixes: ['/crm/audit'],
  },
];

const orgGrowth: ProductSurfaceDefinition[] = [
  {
    id: 'org.campaigns',
    labelKey: 'nav.campaigns.list',
    iconId: 'campaigns',
    path: '/campaigns',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'campaign.view',
    sectionId: 'space-org-growth',
    sectionTitleKey: 'nav.section.campaigns',
    order: 120,
    contextGroup: 'campaigns',
    tabLabel: 'Campañas',
    matchPrefixes: ['/campaigns'],
  },
  {
    id: 'org.business_analytics',
    labelKey: 'nav.businessAnalytics.dashboard',
    iconId: 'activity',
    path: '/business-analytics',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'biz_analytics.view',
    sectionId: 'space-org-growth',
    sectionTitleKey: 'nav.section.campaigns',
    order: 130,
  },
];

const orgRights: ProductSurfaceDefinition[] = [
  {
    id: 'org.royalties',
    labelKey: 'nav.royalties.dashboard',
    iconId: 'contracts',
    path: '/royalties',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'royalty.view',
    sectionId: 'space-org-rights',
    sectionTitleKey: 'nav.section.royalties',
    order: 140,
  },
  {
    id: 'org.payouts',
    labelKey: 'nav.royalties.payouts',
    iconId: 'billing',
    path: '/payouts',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'royalty.view',
    sectionId: 'space-org-rights',
    sectionTitleKey: 'nav.section.royalties',
    order: 150,
  },
];

const orgCs: ProductSurfaceDefinition[] = [
  {
    id: 'org.customer_success',
    labelKey: 'nav.customerSuccess.dashboard',
    iconId: 'team',
    path: '/customer-success',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'customer_success.view',
    sectionId: 'space-org-cs',
    sectionTitleKey: 'nav.section.customerSuccess',
    order: 160,
    contextGroup: 'customerSuccess',
    tabLabel: 'Resumen',
    exact: true,
    matchPrefixes: ['/customer-success'],
  },
  {
    id: 'org.support',
    labelKey: 'nav.customerSuccess.support',
    iconId: 'unresolved_audio',
    path: '/support',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'support.view',
    sectionId: 'space-cs-tabs',
    sectionTitleKey: 'nav.section.customerSuccess',
    order: 170,
    contextGroup: 'customerSuccess',
    tabLabel: 'Soporte',
    matchPrefixes: ['/support'],
  },
];

const orgCompliance: ProductSurfaceDefinition[] = [
  {
    id: 'org.compliance',
    labelKey: 'nav.compliance.privacy',
    iconId: 'settings',
    path: '/compliance',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'compliance.view',
    sectionId: 'space-org-compliance',
    sectionTitleKey: 'nav.section.compliance',
    order: 175,
    exact: true,
    contextGroup: 'compliance',
    tabLabel: 'Privacidad',
  },
  {
    id: 'org.compliance.admin',
    labelKey: 'nav.compliance.admin',
    iconId: 'settings',
    path: '/compliance/admin',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'compliance.manage',
    sectionId: 'space-compliance-tabs',
    sectionTitleKey: 'nav.section.compliance',
    order: 176,
    exact: true,
    contextGroup: 'compliance',
    tabLabel: 'Administración',
  },
];

/** Discoverable org edit/admin tabs (FR-011) — not all appear in sidebar. */
const orgAdminTabs: ProductSurfaceDefinition[] = [
  {
    id: 'org.settings',
    labelKey: 'spaces.nav.org.settings',
    iconId: 'settings',
    path: '/organizations/:id/settings',
    spaces: ['organization'],
    organizationTier: 'onboarding',
    capability: 'organization.view',
    sectionId: 'space-org-admin-tabs',
    sectionTitleKey: 'spaces.nav.org.summary',
    order: 1000,
    contextGroup: 'organization',
    tabLabel: 'Perfil',
    matchPrefixes: ['/organizations/:id/settings'],
  },
  {
    id: 'org.members',
    labelKey: 'spaces.nav.org.members',
    iconId: 'team',
    path: '/organizations/:id/members',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'member.view',
    sectionId: 'space-org-admin-tabs',
    sectionTitleKey: 'spaces.nav.org.summary',
    order: 1010,
    contextGroup: 'organization',
    tabLabel: 'Miembros',
    matchPrefixes: ['/organizations/:id/members'],
  },
  {
    id: 'org.invitations',
    labelKey: 'spaces.nav.org.invitations',
    iconId: 'team',
    path: '/organizations/:id/invitations',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'member.invite',
    sectionId: 'space-org-admin-tabs',
    sectionTitleKey: 'spaces.nav.org.summary',
    order: 1020,
    contextGroup: 'organization',
    tabLabel: 'Invitaciones',
    matchPrefixes: ['/organizations/:id/invitations'],
  },
  {
    id: 'org.roles',
    labelKey: 'spaces.nav.org.roles',
    iconId: 'team',
    path: '/organizations/:id/roles',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'role.view',
    sectionId: 'space-org-admin-tabs',
    sectionTitleKey: 'spaces.nav.org.summary',
    order: 1030,
    contextGroup: 'organization',
    tabLabel: 'Roles y permisos',
    matchPrefixes: ['/organizations/:id/roles'],
  },
  {
    id: 'org.audit',
    labelKey: 'spaces.nav.org.audit',
    iconId: 'activity',
    path: '/organizations/:id/audit',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'audit.view',
    sectionId: 'space-org-admin-tabs',
    sectionTitleKey: 'spaces.nav.org.summary',
    order: 1040,
    contextGroup: 'organization',
    tabLabel: 'Auditoría',
    matchPrefixes: ['/organizations/:id/audit'],
  },
];

const catalogTabs: ProductSurfaceDefinition[] = [
  {
    id: 'catalog.artists',
    labelKey: 'nav.catalog.artists',
    iconId: 'artist',
    path: '/artist-profiles',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'artist.view',
    sectionId: 'space-catalog-tabs',
    sectionTitleKey: 'nav.catalogHub',
    order: 1100,
    contextGroup: 'catalog',
    tabLabel: 'Artistas',
    matchPrefixes: ['/artist-profiles', '/artist/profile'],
  },
  {
    id: 'catalog.tracks',
    labelKey: 'nav.catalog.tracks',
    iconId: 'catalog',
    path: '/artist/tracks',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'publishing.view',
    sectionId: 'space-catalog-tabs',
    sectionTitleKey: 'nav.catalogHub',
    order: 1110,
    contextGroup: 'catalog',
    tabLabel: 'Canciones',
    matchPrefixes: ['/artist/tracks'],
  },
  {
    id: 'catalog.releases',
    labelKey: 'nav.catalog.releases',
    iconId: 'catalog',
    path: '/artist/releases',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'publishing.view',
    sectionId: 'space-catalog-tabs',
    sectionTitleKey: 'nav.catalogHub',
    order: 1120,
    contextGroup: 'catalog',
    tabLabel: 'Lanzamientos',
    matchPrefixes: ['/artist/releases'],
  },
  {
    id: 'catalog.publish',
    labelKey: 'nav.catalog.publish',
    iconId: 'catalog',
    path: '/artist/releases/new',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'publishing.create',
    sectionId: 'space-catalog-tabs',
    sectionTitleKey: 'nav.catalogHub',
    order: 1130,
    exact: true,
    contextGroup: 'catalog',
    tabLabel: 'Publicar música',
    matchPrefixes: ['/artist/releases/new'],
  },
  {
    id: 'catalog.review',
    labelKey: 'nav.catalog.review',
    iconId: 'catalog',
    path: '/catalog-review',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'publishing.review',
    sectionId: 'space-catalog-tabs',
    sectionTitleKey: 'nav.catalogHub',
    order: 1140,
    contextGroup: 'catalog',
    tabLabel: 'Revisiones',
    matchPrefixes: ['/catalog-review'],
  },
  {
    id: 'catalog.rights',
    labelKey: 'nav.catalog.rights',
    iconId: 'contracts',
    path: '/catalog-rights/conflicts',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'rights.view',
    sectionId: 'space-catalog-tabs',
    sectionTitleKey: 'nav.catalogHub',
    order: 1150,
    contextGroup: 'catalog',
    tabLabel: 'Derechos y conflictos',
    matchPrefixes: ['/catalog-rights'],
  },
];

const reportTabs: ProductSurfaceDefinition[] = [
  {
    id: 'reports.simple.org',
    labelKey: 'nav.reports.simple',
    iconId: 'reports',
    path: '/simple-reports',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'report.view',
    sectionId: 'space-report-tabs',
    sectionTitleKey: 'spaces.nav.reports',
    order: 1200,
    contextGroup: 'reports',
    tabLabel: 'Informes simples',
  },
  {
    id: 'reports.complex.org',
    labelKey: 'nav.reports.complex',
    iconId: 'reports',
    path: '/complex-reports',
    spaces: ['organization'],
    organizationTier: 'operational',
    capability: 'report.view',
    sectionId: 'space-report-tabs',
    sectionTitleKey: 'spaces.nav.reports',
    order: 1210,
    contextGroup: 'reports',
    tabLabel: 'Informes complejos',
  },
  {
    id: 'reports.simple.staff',
    labelKey: 'nav.reports.simple',
    iconId: 'reports',
    path: '/simple-reports',
    spaces: ['data_ops', 'platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-report-tabs',
    sectionTitleKey: 'spaces.nav.reports',
    order: 1220,
    contextGroup: 'reports',
    tabLabel: 'Informes simples',
  },
  {
    id: 'reports.complex.staff',
    labelKey: 'nav.reports.complex',
    iconId: 'reports',
    path: '/complex-reports',
    spaces: ['data_ops', 'platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-report-tabs',
    sectionTitleKey: 'spaces.nav.reports',
    order: 1230,
    contextGroup: 'reports',
    tabLabel: 'Informes complejos',
  },
];

const dataOps: ProductSurfaceDefinition[] = [
  {
    id: 'data_ops.workpanel',
    labelKey: 'nav.technicalStatus',
    iconId: 'workpanel',
    path: '/workpanel',
    spaces: ['data_ops'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-data',
    sectionTitleKey: 'spaces.nav.group.dataOps',
    order: 10,
    exact: true,
  },
  {
    id: 'data_ops.elt',
    labelKey: 'nav.eltPipeline',
    iconId: 'elt',
    path: '/elt-pipeline',
    spaces: ['data_ops'],
    staffCapability: STAFF_CAPABILITY.engineering,
    sectionId: 'space-data',
    sectionTitleKey: 'spaces.nav.group.dataOps',
    order: 20,
    exact: true,
    contextGroup: 'engineering',
    tabLabel: 'Ingeniería de datos',
    matchPrefixes: ['/elt-pipeline'],
  },
  {
    id: 'data_ops.explorer',
    labelKey: 'nav.explorer',
    iconId: 'explorer',
    path: '/explorer',
    spaces: ['data_ops'],
    staffCapability: STAFF_CAPABILITY.engineering,
    sectionId: 'space-data',
    sectionTitleKey: 'spaces.nav.group.dataOps',
    order: 30,
    exact: true,
    contextGroup: 'engineering',
    tabLabel: 'Explorador del almacén',
    matchPrefixes: ['/explorer'],
  },
  {
    id: 'data_ops.reports',
    labelKey: 'spaces.nav.reports',
    iconId: 'reports',
    path: '/reports',
    spaces: ['data_ops'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-data',
    sectionTitleKey: 'spaces.nav.group.dataOps',
    order: 40,
    exact: true,
    contextGroup: 'reports',
  },
];

/** Platform Admin — real platform ops only; no organization-scoped commercial without org context. */
const platformAdmin: ProductSurfaceDefinition[] = [
  {
    id: 'platform.workpanel',
    labelKey: 'nav.workpanel',
    iconId: 'workpanel',
    path: '/workpanel',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform',
    sectionTitleKey: 'spaces.nav.group.platform',
    order: 10,
    exact: true,
  },
  {
    id: 'platform.reports',
    labelKey: 'spaces.nav.reports',
    iconId: 'reports',
    path: '/reports',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform',
    sectionTitleKey: 'spaces.nav.group.platform',
    order: 20,
    exact: true,
  },
  {
    id: 'platform.settings',
    labelKey: 'nav.settings',
    iconId: 'settings',
    path: '/settings',
    spaces: ['platform_admin'],
    sectionId: 'space-platform',
    sectionTitleKey: 'spaces.nav.group.platform',
    order: 30,
    exact: true,
  },
  {
    id: 'platform.ops.hub',
    labelKey: 'nav.platformOps.panel',
    iconId: 'workpanel',
    path: '/platform-ops',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform-ops',
    sectionTitleKey: 'nav.section.platformOps',
    order: 40,
    exact: true,
    contextGroup: 'platformOps',
    tabLabel: 'Panel de Ops',
    matchPrefixes: ['/platform-ops'],
  },
  {
    id: 'platform.ops.artist_requests',
    labelKey: 'nav.platformOps.artistRequests',
    iconId: 'artist_requests',
    path: '/platform-ops/artist-requests',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform-ops',
    sectionTitleKey: 'nav.section.platformOps',
    order: 50,
    exact: true,
    contextGroup: 'platformOps',
    tabLabel: 'Solicitudes de artista',
    matchPrefixes: ['/platform-ops/artist-requests'],
  },
  {
    id: 'platform.ops.catalog_reviews',
    labelKey: 'nav.platformOps.catalogReviews',
    iconId: 'catalog',
    path: '/platform-ops/catalog-reviews',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform-ops',
    sectionTitleKey: 'nav.section.platformOps',
    order: 60,
    exact: false,
    contextGroup: 'platformOps',
    tabLabel: 'Revisiones',
    matchPrefixes: ['/platform-ops/catalog-reviews'],
  },
  {
    id: 'platform.ops.audio_unresolved',
    labelKey: 'nav.platformOps.audioUnresolved',
    iconId: 'unresolved_audio',
    path: '/platform-ops/audio-unresolved',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform-ops',
    sectionTitleKey: 'nav.section.platformOps',
    order: 70,
    exact: true,
    contextGroup: 'platformOps',
    tabLabel: 'Audio no resuelto',
    matchPrefixes: ['/platform-ops/audio-unresolved'],
  },
  {
    id: 'platform.ops.system',
    labelKey: 'nav.platformOps.system',
    iconId: 'settings',
    path: '/platform-ops/system',
    spaces: ['platform_admin'],
    staffCapability: STAFF_CAPABILITY.shell,
    sectionId: 'space-platform-ops',
    sectionTitleKey: 'nav.section.platformOps',
    order: 80,
    exact: true,
    contextGroup: 'platformOps',
    tabLabel: 'Sistema',
    matchPrefixes: ['/platform-ops/system'],
  },
];

const artist: ProductSurfaceDefinition[] = [
  {
    id: 'artist.summary',
    labelKey: 'spaces.nav.artist.summary',
    iconId: 'home',
    path: '/artist-space',
    spaces: ['artist'],
    sectionId: 'space-artist',
    sectionTitleKey: 'spaces.nav.group.artist',
    order: 10,
    exact: true,
  },
  {
    id: 'artist.profile',
    labelKey: 'spaces.nav.artist.profile',
    iconId: 'artist',
    path: '/artist-space/profile',
    spaces: ['artist'],
    capability: 'artist_space.view',
    sectionId: 'space-artist',
    sectionTitleKey: 'spaces.nav.group.artist',
    order: 20,
    exact: true,
  },
  {
    id: 'artist.music',
    labelKey: 'spaces.nav.artist.music',
    iconId: 'catalog',
    path: '/artist-space/music',
    spaces: ['artist'],
    capability: 'artist_space.catalog.view',
    sectionId: 'space-artist',
    sectionTitleKey: 'spaces.nav.group.artist',
    order: 30,
    exact: false,
  },
  {
    id: 'artist.team',
    labelKey: 'spaces.nav.artist.team',
    iconId: 'team',
    path: '/artist-space/team',
    spaces: ['artist'],
    capability: 'artist_space.view',
    sectionId: 'space-artist',
    sectionTitleKey: 'spaces.nav.group.artist',
    order: 40,
    exact: true,
  },
];

/** Single authority for all product surfaces. */
export const PRODUCT_SURFACE_REGISTRY: readonly ProductSurfaceDefinition[] = [
  ...personalMain,
  ...personalLibrary,
  ...personalAccount(['personal', 'organization'], true),
  ...personalAccount(['platform_admin'], false),
  ...personalEntry,
  ...orgMain,
  ...orgPlanBilling,
  ...orgCrm,
  ...orgGrowth,
  ...orgRights,
  ...orgCs,
  ...orgCompliance,
  ...orgAdminTabs,
  ...catalogTabs,
  ...reportTabs,
  ...dataOps,
  ...platformAdmin,
  ...artist,
];

export function productSurfacesForSpace(kind: ProductSurfaceDefinition['spaces'][number]): ProductSurfaceDefinition[] {
  return PRODUCT_SURFACE_REGISTRY.filter((s) => s.spaces.includes(kind)).sort(
    (a, b) => a.order - b.order || a.id.localeCompare(b.id),
  );
}
